### ISSUE TITLE
B5 - Currency exchange

### ISSUE THREAD

**Issue by ijevtic** [RAF-SI-2023/Banka-1-Backend#152]

**Comment by ijevtic** [comment]
Specifikacija strana 92

**Comment by tismadusan567** [comment]
Dodati kursnu listu u model. Povuci podatke sa apija i ubaciti u bazu. Dodati transfer u model. Omoguciti funkcionalnost menjacnice i napraviti endpointe za nju, kao i za upite ka kursnoj listi i istoriji transfera
