### ISSUE TITLE
B4 - Creating/Approving orders on market

### ISSUE THREAD

**Issue by ijevtic** [RAF-SI-2023/Banka-1-Backend#154]
Strana 24 specifikacija. Pod ovim se podrazumeva i:
Novi tipovi korisnika - Imamo aktuare i supervizore, jedni nemaju limit, drugi imaju, treba odvojiti ove 2 kategoriji u entitetu User(zaposleni). Moguce da je dovoljno samo kreirati dodatnu kolonu. Procitati na strani 32(nije potrebno implementirati izmenu porudzbine, vec samo da se razume).
Setovanje limita
Entitet porudzbina

**Comment by mihailot01** [comment]
Poruzbina treba da ima status koji moze biti: odobrena(approved), ceka odobrenje(processing), zavrsena(done), odbijena(denied).

**Comment by mihailot01** [comment]
Dodati status cancled, dodati polje koliko je hartija vec obradjeno (kupljeno/prodato)
