### ISSUE TITLE
B4 - Changing the Order, Reseting the limit on the actors

### ISSUE THREAD

**Issue by ijevtic** [RAF-SI-2023/Banka-1-Backend#155]
Specifikacija strana 32

**Comment by tismadusan567** [comment]
Aktuari i supervizori + dodati nove atribute i izmenu i kreiranje korisnika. Resetovanje limita - periodicno + endpoint. Endpoint za setovanje limita. Izmena sistema za porudzbine - update modela. Cela logika izmene sistema za porudzbine + odgovarajuci kontroleri.
