### ISSUE TITLE
B4 - Endpoint for checking if the exchange works for a given time

### ISSUE THREAD

**Issue by ijevtic** [RAF-SI-2023/Banka-1-Backend#163]
specifikacija strana 28. Treba nam endpoint koji nam vraca da li u to vreme radi exchange, da bi se znalo koliko brzo se izvrsava porudzbina. Napraviti endpoint, dodati u endpoints fajl(prima se 99% exhange id, zbog formata tickera).

**Comment by tismadusan567** [comment]
Informacija da li u neko vreme radi exchange se izvlaci iz country tabele u bazi, obratite paznju da moze biti null dosta cesto. Takodje uzeti u obzir praznike, koji su sacuvani u holidays tabeli i vezani za drzavu
