### ISSUE TITLE
B4 - Seperate routes for login, fix Employee and Customer objects

### ISSUE THREAD

**Issue by ijevtic** [RAF-SI-2023/Banka-1-Backend#166]
Polje position kod zaposlenog znaci nesto, kod korisnika ne znaci nista. Trenutno ga koristimo da napravimo distinkciju izmedju korisnika i zaposlenog, ali ovo nije dobro. Promeniti tipove tako da se slazu po specifikaciji, napraviti 2 rute za login, sve dodati u endpoints fajl.

**Comment by tismadusan567** [comment]
Kad budete radili login posaljite mi poruku
